"""add user profile and preferences

Revision ID: e71ad18439eb
Revises: 51f951ae16d7
Create Date: 2026-09-18 05:00:22.351717
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e71ad18439eb'
down_revision: str | None = '51f951ae16d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('response_style', sa.String(length=20), nullable=False),
    sa.Column('ai_suggestions', sa.Boolean(), nullable=False),
    sa.Column('recall_suggestions', sa.Boolean(), nullable=False),
    sa.Column('knowledge_visibility', sa.String(length=20), nullable=False),
    sa.Column('ai_processing_mode', sa.String(length=10), nullable=False),
    sa.Column('local_provider', sa.String(length=60), nullable=True),
    sa.Column('local_model', sa.String(length=120), nullable=True),
    sa.Column('cloud_provider', sa.String(length=60), nullable=True),
    sa.Column('cloud_model', sa.String(length=120), nullable=True),
    sa.Column('cloud_ai_consent', sa.Boolean(), nullable=False),
    sa.Column('cloud_ai_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('organization', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('expertise', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('current_topics', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('learning_goals', sa.Text(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
